{"id":167688,"global_id":"Z2lkOi8vaGFja2Vyb25lL1JlcG9ydC8xNjc2ODg=","url":"https://hackerone.com/reports/167688","title":"msilib.OpenDatabase Type Confusion","state":"Closed","substate":"resolved","readable_substate":"Resolved","created_at":"2016-09-12T04:21:54.616Z","submitted_at":"2016-09-12T04:21:54.616Z","is_member_of_team?":false,"reporter":{"disabled":false,"username":"johnleitch","url":"/johnleitch","profile_picture_urls":{"small":"/assets/avatars/default-71a302d706457f3d3a31eb30fa3e73e6cf0b1d677b8fa218eaeaffd67ae97918.png"},"is_me?":false,"cleared":false,"hackerone_triager":false,"hacker_mediation":false},"team":{"id":27,"url":"https://hackerone.com/ibb-python","handle":"ibb-python","profile_picture_urls":{"small":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/3afcb5c896247e7ee8ada31b1c1eb8657e22241f911093acfe4ec7e97a3a959a","medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"permissions":[],"submission_state":"open","default_currency":"usd","awards_miles":false,"offers_bounties":true,"state":"public_mode","only_cleared_hackers":false,"profile":{"name":"Python (IBB)","twitter_handle":"","website":"http://www.python.org/news/security","about":""}},"has_bounty?":true,"in_validation?":false,"rejected_anc_report_that_can_be_sent_back_to_anc_triagers?":false,"can_view_team":true,"can_view_report":true,"is_external_bug":false,"is_published":false,"is_participant":false,"stage":4,"public":true,"visibility":"full","cve_ids":[],"singular_disclosure_disabled":false,"disclosed_at":"2016-09-20T05:38:52.437Z","bug_reporter_agreed_on_going_public_at":"2016-09-20T05:37:29.448Z","team_member_agreed_on_going_public_at":"2016-09-20T05:38:52.358Z","comments_closed?":false,"facebook_team?":false,"team_private?":false,"vulnerability_information":"I have reported a vulnerability in Python that is now fixed. My patch was accepted with minor changes.\n\n---\n\nhttp://bugs.python.org/issue24594\n\nThe msilib.OpenDatabase method suffers from a type confusion vulnerability caused by the behavior of MsiOpenDatabase(), the underlying win32 function utilized. This is due to the unorthodox handling of the szPersist parameter: when an MSIDBOPEN_* value is passed, it is treated as a predefined persistence mode. However, when a larger value is passed, it is treated as a string pointer, which is used as the path to a new file.\n\nBecause the Python method msilib.OpenDatabase passes its persist parameter through to MsiOpenDatabase, it may be possible for an attacker to trigger the type confusion bug should the seemingly innocuous persist parameter be exposed as attack surface. This could have a few consequences: \n\n1) An attacker might be able to leverage this vulnerability to probe for valid addresses, which could then be used in another exploit to bypass ASLR/DEP.\n2) An attacker might be able to leverage this vulnerability to dereference aribtrary values in memory, disclosing secrets. \n3) An attacker may be able to spray memory with specially crafted string values, then leverage this vulnerability to pass one of the values as a persist string. Because this would lead to the creation of an MSI file in a location now controlled by the attacker, it could potentially be exploited to achieve remote code execution.\n\nA Python script that demonstrates the vulnerability is as follows:\n\nimport msilib\nmsilib.OpenDatabase(\"\",0x41414141)\n\nAnd it produces the following exception:\n\n0:000\u003e r\neax=41414141 ebx=00000000 ecx=0027f8c0 edx=41414142 esi=0027f8c0 edi=00000000\neip=757252aa esp=0027f874 ebp=0027f89c iopl=0         nv up ei pl zr na pe nc\ncs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246\nKERNELBASE!lstrlenA+0x1a:\n757252aa 8a08            mov     cl,byte ptr [eax]          ds:002b:41414141=??\n0:000\u003e !analyze -v -nodb\n*******************************************************************************\n*                                                                             *\n*                        Exception Analysis                                   *\n*                                                                             *\n*******************************************************************************\n\n\nFAULTING_IP: \nKERNELBASE!lstrlenA+1a\n757252aa 8a08            mov     cl,byte ptr [eax]\n\nEXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)\nExceptionAddress: 757252aa (KERNELBASE!lstrlenA+0x0000001a)\n   ExceptionCode: c0000005 (Access violation)\n  ExceptionFlags: 00000000\nNumberParameters: 2\n   Parameter[0]: 00000000\n   Parameter[1]: 41414141\nAttempt to read from address 41414141\n\nCONTEXT:  00000000 -- (.cxr 0x0;r)\neax=41414141 ebx=00000000 ecx=0027f8c0 edx=41414142 esi=0027f8c0 edi=00000000\neip=757252aa esp=0027f874 ebp=0027f89c iopl=0         nv up ei pl zr na pe nc\ncs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246\nKERNELBASE!lstrlenA+0x1a:\n757252aa 8a08            mov     cl,byte ptr [eax]          ds:002b:41414141=??\n\nFAULTING_THREAD:  00000d38\n\nPROCESS_NAME:  python.exe\n\nERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.\n\nEXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.\n\nEXCEPTION_PARAMETER1:  00000000\n\nEXCEPTION_PARAMETER2:  41414141\n\nREAD_ADDRESS:  41414141 \n\nFOLLOWUP_IP: \nmsi!CApiConvertString::operator unsigned short const *+1b1d\n622e1fa1 40              inc     eax\n\nNTGLOBALFLAG:  70\n\nAPPLICATION_VERIFIER_FLAGS:  0\n\nAPP:  python.exe\n\nANALYSIS_VERSION: 6.3.9600.17029 (debuggers(dbg).140219-1702) x86fre\n\nBUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_41414141\n\nPRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ_FILL_PATTERN_41414141\n\nDEFAULT_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_41414141\n\nLAST_CONTROL_TRANSFER:  from 622e1fa1 to 757252aa\n\nSTACK_TEXT:  \n0027f89c 622e1fa1 41414141 41414141 623e22d0 KERNELBASE!lstrlenA+0x1a\n0027fcfc 1d162217 01c54334 41414141 0027fd10 msi!CApiConvertString::operator unsigned short const *+0x1b1d\n0027fd18 1e0aafd7 00000000 01d86940 01d7ea08 _msi!msiopendb+0x37\n0027fd30 1e0edd10 01d7ea08 01d86940 00000000 python27!PyCFunction_Call+0x47\n0027fd5c 1e0f017a 0027fdb4 01c86b18 01c86b18 python27!call_function+0x2b0\n0027fdcc 1e0f1150 01cb4030 00000000 01c86b18 python27!PyEval_EvalFrameEx+0x239a\n0027fe00 1e0f11b2 01c86b18 01cb4030 01c8aa50 python27!PyEval_EvalCodeEx+0x690\n0027fe2c 1e11707a 01c86b18 01c8aa50 01c8aa50 python27!PyEval_EvalCode+0x22\n0027fe44 1e1181c5 01d43a20 01c8aa50 01c8aa50 python27!run_mod+0x2a\n0027fe64 1e118760 68e87408 003f2e93 00000101 python27!PyRun_FileExFlags+0x75\n0027fea4 1e1190d9 68e87408 003f2e93 00000001 python27!PyRun_SimpleFileExFlags+0x190\n0027fec0 1e038d35 68e87408 003f2e93 00000001 python27!PyRun_AnyFileExFlags+0x59\n0027ff3c 1d00116d 00000002 003f2e70 003f1940 python27!Py_Main+0x965\n0027ff80 75847c04 7ffde000 75847be0 0c2f39c0 python!__tmainCRTStartup+0x10f\n0027ff94 77c9b90f 7ffde000 0e681648 00000000 KERNEL32!BaseThreadInitThunk+0x24\n0027ffdc 77c9b8da ffffffff 77c806e0 00000000 ntdll!__RtlUserThreadStart+0x2f\n0027ffec 00000000 1d001314 7ffde000 00000000 ntdll!_RtlUserThreadStart+0x1b\n\n\nSTACK_COMMAND:  .cxr 0x0 ; kb\n\nSYMBOL_STACK_INDEX:  1\n\nSYMBOL_NAME:  msi!CApiConvertString::operator unsigned short const *+1b1d\n\nFOLLOWUP_NAME:  MachineOwner\n\nMODULE_NAME: msi\n\nIMAGE_NAME:  msi.dll\n\nDEBUG_FLR_IMAGE_TIMESTAMP:  5450468f\n\nFAILURE_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_41414141_c0000005_msi.dll!CApiConvertString::operator_unsigned_short_const_*\n\nBUCKET_ID:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_41414141_msi!CApiConvertString::operator_unsigned_short_const_*+1b1d\n\nANALYSIS_SOURCE:  UM\n\nFAILURE_ID_HASH_STRING:  um:invalid_pointer_read_fill_pattern_41414141_c0000005_msi.dll!capiconvertstring::operator_unsigned_short_const_*\n\nFAILURE_ID_HASH:  {11693fba-32c4-0880-2440-574cbd780159}\n\nFollowup: MachineOwner\n---------\n\nTo fix the issue, msiopendb() should perform whitelist validation of the persist value to confirm that it is a valid MSIDBOPEN_* constant. A proposed patch is attached.","vulnerability_information_html":"\u003cp\u003eI have reported a vulnerability in Python that is now fixed. My patch was accepted with minor changes.\u003c/p\u003e\n\n\u003chr\u003e\n\n\u003cp\u003e\u003ca title=\"http://bugs.python.org/issue24594\" href=\"/redirect?url=http%3A%2F%2Fbugs.python.org%2Fissue24594\" target=\"_blank\" rel=\"nofollow noopener noreferrer\"\u003e\u003cspan\u003ehttp://bugs.python.org/issue24594\u003c/span\u003e\u003ci class=\"icon-external-link\"\u003e\u003c/i\u003e\u003c/a\u003e\u003c/p\u003e\n\n\u003cp\u003eThe msilib.OpenDatabase method suffers from a type confusion vulnerability caused by the behavior of MsiOpenDatabase(), the underlying win32 function utilized. This is due to the unorthodox handling of the szPersist parameter: when an MSIDBOPEN_* value is passed, it is treated as a predefined persistence mode. However, when a larger value is passed, it is treated as a string pointer, which is used as the path to a new file.\u003c/p\u003e\n\n\u003cp\u003eBecause the Python method msilib.OpenDatabase passes its persist parameter through to MsiOpenDatabase, it may be possible for an attacker to trigger the type confusion bug should the seemingly innocuous persist parameter be exposed as attack surface. This could have a few consequences: \u003c/p\u003e\n\n\u003cp\u003e1) An attacker might be able to leverage this vulnerability to probe for valid addresses, which could then be used in another exploit to bypass ASLR/DEP.\u003cbr\u003e\n2) An attacker might be able to leverage this vulnerability to dereference aribtrary values in memory, disclosing secrets. \u003cbr\u003e\n3) An attacker may be able to spray memory with specially crafted string values, then leverage this vulnerability to pass one of the values as a persist string. Because this would lead to the creation of an MSI file in a location now controlled by the attacker, it could potentially be exploited to achieve remote code execution.\u003c/p\u003e\n\n\u003cp\u003eA Python script that demonstrates the vulnerability is as follows:\u003c/p\u003e\n\n\u003cp\u003eimport msilib\u003cbr\u003e\nmsilib.OpenDatabase(\u0026quot;\u0026quot;,0x41414141)\u003c/p\u003e\n\n\u003cp\u003eAnd it produces the following exception:\u003c/p\u003e\n\n\u003cp\u003e0:000\u0026gt; r\u003cbr\u003e\neax=41414141 ebx=00000000 ecx=0027f8c0 edx=41414142 esi=0027f8c0 edi=00000000\u003cbr\u003e\neip=757252aa esp=0027f874 ebp=0027f89c iopl=0         nv up ei pl zr na pe nc\u003cbr\u003e\ncs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246\u003cbr\u003e\nKERNELBASE!lstrlenA+0x1a:\u003cbr\u003e\n757252aa 8a08            mov     cl,byte ptr [eax]          ds:002b:41414141=??\u003cbr\u003e\n0:000\u0026gt; !analyze -v -nodb\u003c/p\u003e\n\n\u003chr\u003e\n\n\u003cul\u003e\n\u003cli\u003e                                                                            *\u003c/li\u003e\n\u003cli\u003e                       Exception Analysis                                   *\u003c/li\u003e\n\u003cli\u003e                                                                            *\n*******************************************************************************\u003c/li\u003e\n\u003c/ul\u003e\n\n\u003cp\u003eFAULTING_IP: \u003cbr\u003e\nKERNELBASE!lstrlenA+1a\u003cbr\u003e\n757252aa 8a08            mov     cl,byte ptr [eax]\u003c/p\u003e\n\n\u003cp\u003eEXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)\u003cbr\u003e\nExceptionAddress: 757252aa (KERNELBASE!lstrlenA+0x0000001a)\u003cbr\u003e\n   ExceptionCode: c0000005 (Access violation)\u003cbr\u003e\n  ExceptionFlags: 00000000\u003cbr\u003e\nNumberParameters: 2\u003cbr\u003e\n   Parameter[0]: 00000000\u003cbr\u003e\n   Parameter[1]: 41414141\u003cbr\u003e\nAttempt to read from address 41414141\u003c/p\u003e\n\n\u003cp\u003eCONTEXT:  00000000 -- (.cxr 0x0;r)\u003cbr\u003e\neax=41414141 ebx=00000000 ecx=0027f8c0 edx=41414142 esi=0027f8c0 edi=00000000\u003cbr\u003e\neip=757252aa esp=0027f874 ebp=0027f89c iopl=0         nv up ei pl zr na pe nc\u003cbr\u003e\ncs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246\u003cbr\u003e\nKERNELBASE!lstrlenA+0x1a:\u003cbr\u003e\n757252aa 8a08            mov     cl,byte ptr [eax]          ds:002b:41414141=??\u003c/p\u003e\n\n\u003cp\u003eFAULTING_THREAD:  00000d38\u003c/p\u003e\n\n\u003cp\u003ePROCESS_NAME:  python.exe\u003c/p\u003e\n\n\u003cp\u003eERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.\u003c/p\u003e\n\n\u003cp\u003eEXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.\u003c/p\u003e\n\n\u003cp\u003eEXCEPTION_PARAMETER1:  00000000\u003c/p\u003e\n\n\u003cp\u003eEXCEPTION_PARAMETER2:  41414141\u003c/p\u003e\n\n\u003cp\u003eREAD_ADDRESS:  41414141 \u003c/p\u003e\n\n\u003cp\u003eFOLLOWUP_IP: \u003cbr\u003e\nmsi!CApiConvertString::operator unsigned short const *+1b1d\u003cbr\u003e\n622e1fa1 40              inc     eax\u003c/p\u003e\n\n\u003cp\u003eNTGLOBALFLAG:  70\u003c/p\u003e\n\n\u003cp\u003eAPPLICATION_VERIFIER_FLAGS:  0\u003c/p\u003e\n\n\u003cp\u003eAPP:  python.exe\u003c/p\u003e\n\n\u003cp\u003eANALYSIS_VERSION: 6.3.9600.17029 (debuggers(dbg).140219-1702) x86fre\u003c/p\u003e\n\n\u003cp\u003eBUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_41414141\u003c/p\u003e\n\n\u003cp\u003ePRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ_FILL_PATTERN_41414141\u003c/p\u003e\n\n\u003cp\u003eDEFAULT_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_41414141\u003c/p\u003e\n\n\u003cp\u003eLAST_CONTROL_TRANSFER:  from 622e1fa1 to 757252aa\u003c/p\u003e\n\n\u003cp\u003eSTACK_TEXT:\u003cbr\u003e\u003cbr\u003e\n0027f89c 622e1fa1 41414141 41414141 623e22d0 KERNELBASE!lstrlenA+0x1a\u003cbr\u003e\n0027fcfc 1d162217 01c54334 41414141 0027fd10 msi!CApiConvertString::operator unsigned short const *+0x1b1d\u003cbr\u003e\n0027fd18 1e0aafd7 00000000 01d86940 01d7ea08 \u003cu\u003emsi!msiopendb+0x37\u003cbr\u003e\n0027fd30 1e0edd10 01d7ea08 01d86940 00000000 python27!PyCFunction_Call+0x47\u003cbr\u003e\n0027fd5c 1e0f017a 0027fdb4 01c86b18 01c86b18 python27!call_function+0x2b0\u003cbr\u003e\n0027fdcc 1e0f1150 01cb4030 00000000 01c86b18 python27!PyEval_EvalFrameEx+0x239a\u003cbr\u003e\n0027fe00 1e0f11b2 01c86b18 01cb4030 01c8aa50 python27!PyEval_EvalCodeEx+0x690\u003cbr\u003e\n0027fe2c 1e11707a 01c86b18 01c8aa50 01c8aa50 python27!PyEval_EvalCode+0x22\u003cbr\u003e\n0027fe44 1e1181c5 01d43a20 01c8aa50 01c8aa50 python27!run_mod+0x2a\u003cbr\u003e\n0027fe64 1e118760 68e87408 003f2e93 00000101 python27!PyRun_FileExFlags+0x75\u003cbr\u003e\n0027fea4 1e1190d9 68e87408 003f2e93 00000001 python27!PyRun_SimpleFileExFlags+0x190\u003cbr\u003e\n0027fec0 1e038d35 68e87408 003f2e93 00000001 python27!PyRun_AnyFileExFlags+0x59\u003cbr\u003e\n0027ff3c 1d00116d 00000002 003f2e70 003f1940 python27!Py_Main+0x965\u003cbr\u003e\n0027ff80 75847c04 7ffde000 75847be0 0c2f39c0 python!\u003c/u\u003e\u003cu\u003etmainCRTStartup+0x10f\u003cbr\u003e\n0027ff94 77c9b90f 7ffde000 0e681648 00000000 KERNEL32!BaseThreadInitThunk+0x24\u003cbr\u003e\n0027ffdc 77c9b8da ffffffff 77c806e0 00000000 ntdll!\u003c/u\u003e_RtlUserThreadStart+0x2f\u003cbr\u003e\n0027ffec 00000000 1d001314 7ffde000 00000000 ntdll!_RtlUserThreadStart+0x1b\u003c/p\u003e\n\n\u003cp\u003eSTACK_COMMAND:  .cxr 0x0 ; kb\u003c/p\u003e\n\n\u003cp\u003eSYMBOL_STACK_INDEX:  1\u003c/p\u003e\n\n\u003cp\u003eSYMBOL_NAME:  msi!CApiConvertString::operator unsigned short const *+1b1d\u003c/p\u003e\n\n\u003cp\u003eFOLLOWUP_NAME:  MachineOwner\u003c/p\u003e\n\n\u003cp\u003eMODULE_NAME: msi\u003c/p\u003e\n\n\u003cp\u003eIMAGE_NAME:  msi.dll\u003c/p\u003e\n\n\u003cp\u003eDEBUG_FLR_IMAGE_TIMESTAMP:  5450468f\u003c/p\u003e\n\n\u003cp\u003eFAILURE_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_41414141_c0000005_msi.dll!CApiConvertString::operator_unsigned_short_const_*\u003c/p\u003e\n\n\u003cp\u003eBUCKET_ID:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_41414141_msi!CApiConvertString::operator_unsigned_short_const_*+1b1d\u003c/p\u003e\n\n\u003cp\u003eANALYSIS_SOURCE:  UM\u003c/p\u003e\n\n\u003cp\u003eFAILURE_ID_HASH_STRING:  um:invalid_pointer_read_fill_pattern_41414141_c0000005_msi.dll!capiconvertstring::operator_unsigned_short_const_*\u003c/p\u003e\n\n\u003cp\u003eFAILURE_ID_HASH:  {11693fba-32c4-0880-2440-574cbd780159}\u003c/p\u003e\n\n\u003ch2 id=\"followup-machineowner\"\u003eFollowup: MachineOwner\u003c/h2\u003e\n\n\u003cp\u003eTo fix the issue, msiopendb() should perform whitelist validation of the persist value to confirm that it is a valid MSIDBOPEN_* constant. A proposed patch is attached.\u003c/p\u003e\n","bounty_amount":"1000.0","formatted_bounty":"$1,000","weakness":{"id":70,"name":"Code Injection"},"original_report_id":null,"original_report_url":null,"attachments":[],"allow_singular_disclosure_at":"2016-10-20T05:37:29.583Z","allow_singular_disclosure_after":-132274931.61266024,"singular_disclosure_allowed":true,"vote_count":1,"voters":["dyabla"],"structured_scope":null,"abilities":{"assignable_team_members":[],"assignable_team_member_groups":[]},"can_edit_custom_fields_attributes":false,"activities":[{"id":1205690,"is_internal":false,"editable":false,"type":"Activities::BugResolved","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T04:04:05.009Z","updated_at":"2016-09-20T04:04:05.009Z","actor":{"username":"arice","cleared":false,"url":"/arice","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/020/83152cb2d070f3f6a63c1b61bae47257722b5ad2_original.jpeg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"reporter":{"username":"johnleitch","url":"/johnleitch"},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205691,"is_internal":false,"editable":false,"type":"Activities::BountyAwarded","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T04:04:11.457Z","updated_at":"2016-09-20T04:04:11.457Z","actor":{"url":"/ibb-python","ibb":true,"profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/027/c46b79d4c73a7b34d61a717ed19ae719a0b67b2e_original.png/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"profile":{"name":"Python (IBB)"}},"bounty_amount":"1000.0","bounty_currency":"usd","genius_execution_id":null,"team_handle":"ibb-python","collaborator":{"username":"johnleitch","url":"/johnleitch"},"actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205942,"is_internal":false,"editable":false,"type":"Activities::AgreedOnGoingPublic","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T05:37:29.480Z","updated_at":"2016-09-20T05:37:29.480Z","first_to_agree":true,"actor":{"username":"johnleitch","cleared":false,"url":"/johnleitch","profile_picture_urls":{"medium":"/assets/avatars/default-71a302d706457f3d3a31eb30fa3e73e6cf0b1d677b8fa218eaeaffd67ae97918.png"},"hackerone_triager":false,"hackerone_employee":false},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205944,"is_internal":false,"editable":false,"type":"Activities::AgreedOnGoingPublic","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T05:38:52.396Z","updated_at":"2016-09-20T05:38:52.396Z","actor":{"username":"arice","cleared":false,"url":"/arice","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/020/83152cb2d070f3f6a63c1b61bae47257722b5ad2_original.jpeg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false},{"id":1205945,"is_internal":false,"editable":false,"type":"Activities::ReportBecamePublic","message":"","markdown_message":"","automated_response":false,"created_at":"2016-09-20T05:38:52.488Z","updated_at":"2016-09-20T05:38:52.488Z","actor":{"username":"arice","cleared":false,"url":"/arice","profile_picture_urls":{"medium":"https://profile-photos.hackerone-user-content.com/variants/000/000/020/83152cb2d070f3f6a63c1b61bae47257722b5ad2_original.jpeg/eb31823a4cc9f6b6bb4db930ffdf512533928a68a4255fb50a83180281a60da5"},"hackerone_triager":false,"hackerone_employee":true},"genius_execution_id":null,"team_handle":"ibb-python","actor_is_team_member":false,"actor_is_concealed_member":false}],"activity_page_count":1,"activity_page_number":1,"summaries":[{"category":"team","can_view?":true,"can_create?":false},{"category":"researcher","can_view?":true,"can_create?":false}]}